// printMockApi — prints the mock dev.modaal:mocks-processor generates for each target, without
// compiling the module.
//
//   ./gradlew -I <this file> :<module>:printMockApi -q
//   ./gradlew -I <this file> :<module>:printMockApi -q -PmockApiTargets=com.example.Repository
//
// Registers the task on every project that applies com.google.devtools.ksp and edits no build
// file. It reads the module's existing wiring — the mocks-processor dependency on its test-side
// KSP configuration, kspMocksTargets from its ksp {} block, and the KSP version of the applied KSP
// Gradle plugin — and runs KSP's command-line entry point over the module's sources into
// build/tmp/printMockApi/, which no source set reads. For each target it prints `// <fqn>`, the
// generated <Interface>Mock.kt, and a blank line.
//
// The plan and the measurements behind it: specs/003-print-mock-api/spec.md in
// https://github.com/modaal-agent/kotlin-ksp-mocks.

import java.io.File

allprojects {
  val module = this
  module.plugins.withId("com.google.devtools.ksp") {
    module.tasks.register("printMockApi", JavaExec::class.java) {
      configurePrintMockApi(module, this)
    }
  }
}

// One module shape: the configuration the processor is declared on, the source sets KSP reads, the
// ones among them that are common code, and the configuration their libraries resolve from.
class Shape(
  val processorConfiguration: String,
  val sourceSets: List<String>,
  val commonSourceSets: List<String>,
  val libraries: String,
)

fun configurePrintMockApi(module: Project, task: JavaExec) {
  val path = module.path
  val multiplatform = module.plugins.hasPlugin("org.jetbrains.kotlin.multiplatform")
  if (!multiplatform && !module.plugins.hasPlugin("org.jetbrains.kotlin.jvm")) {
    throw GradleException(
      "printMockApi: $path applies neither org.jetbrains.kotlin.jvm nor org.jetbrains.kotlin.multiplatform — " +
        "the task supports Kotlin/JVM and Kotlin Multiplatform modules")
  }

  val shapes = if (multiplatform) {
    listOf(Shape("kspJvmTest", listOf("commonMain", "jvmMain", "commonTest", "jvmTest"), listOf("commonMain", "commonTest"), "jvmTestCompileClasspath"))
  } else {
    listOf(
      Shape("kspTest", listOf("main", "test"), emptyList(), "testCompileClasspath"),
      Shape("kspTestFixtures", listOf("main", "testFixtures"), emptyList(), "testFixturesCompileClasspath"),
    )
  }
  val found = shapes.firstNotNullOfOrNull { shape ->
    module.configurations.findByName(shape.processorConfiguration)
      ?.dependencies?.firstOrNull { it.name == "mocks-processor" }
      ?.let { shape to it }
  } ?: throw GradleException(
    "printMockApi: $path has no mocks-processor on ${shapes.joinToString(" or ") { it.processorConfiguration }}")
  val (shape, processor) = found

  // The KSP and Kotlin Gradle plugins are loaded by the build's class loaders, not this script's, so
  // their members are reached by name.
  val kspPlugin = module.plugins.getPlugin("com.google.devtools.ksp")
  val kspVersion = reflect(path, "com.google.devtools.ksp.gradle.KSPVersionsKt.getKSP_VERSION") {
    kspPlugin.javaClass.classLoader.loadClass("com.google.devtools.ksp.gradle.KSPVersionsKt")
      .getMethod("getKSP_VERSION").invoke(null) as String
  }
  val kspExtension = module.extensions.getByName("ksp")
  @Suppress("UNCHECKED_CAST")
  val kspArguments = reflect(path, "${kspExtension.javaClass.name}.getArguments") {
    kspExtension.javaClass.getMethod("getArguments").invoke(kspExtension) as Map<String, String>
  }
  val targets = (module.providers.gradleProperty("mockApiTargets").orNull ?: kspArguments["kspMocksTargets"].orEmpty())
    .split(',').map(String::trim).filter(String::isNotEmpty)
  if (targets.isEmpty()) {
    throw GradleException(
      "printMockApi: $path names no interface in kspMocksTargets — pass -PmockApiTargets=<fqn>,<fqn>")
  }

  val kotlinExtension = module.extensions.getByName("kotlin")
  val coreLibrariesVersion = reflect(path, "${kotlinExtension.javaClass.name}.getCoreLibrariesVersion") {
    kotlinExtension.javaClass.getMethod("getCoreLibrariesVersion").invoke(kotlinExtension) as String
  }
  val languageVersion = coreLibrariesVersion.split('.').take(2).joinToString(".")

  val kotlinSourceSets = if (multiplatform) {
    reflect(path, "${kotlinExtension.javaClass.name}.getSourceSets") {
      kotlinExtension.javaClass.getMethod("getSourceSets").invoke(kotlinExtension) as NamedDomainObjectContainer<*>
    }
  } else {
    null
  }
  // KSP adds its own output directories to these source sets; a mock generated by an earlier test
  // compilation is left out, so the run does not read the declaration it is about to write.
  val generatedByKsp = module.layout.buildDirectory.dir("generated/ksp").get().asFile
  fun kotlinDirectories(sourceSet: String): List<File> {
    val directories = if (kotlinSourceSets != null) {
      kotlinSourceSets.findByName(sourceSet)?.let { set ->
        reflect(path, "${set.javaClass.name}.getKotlin") {
          set.javaClass.getMethod("getKotlin").invoke(set) as SourceDirectorySet
        }
      }
    } else {
      module.extensions.getByType(SourceSetContainer::class.java).findByName(sourceSet)
        ?.extensions?.findByName("kotlin") as SourceDirectorySet?
    }
    return directories?.srcDirs.orEmpty().filter { it.isDirectory && !it.startsWith(generatedByKsp) }
  }
  val sources = module.files(shape.sourceSets.flatMap(::kotlinDirectories))
  val commonSources = module.files(shape.commonSourceSets.flatMap(::kotlinDirectories))

  // The module's own outputs are left out of the libraries: its sources are read directly, and
  // building them would run the module's compilation. `java-test-fixtures` puts the module's jar on
  // the classpath, and a multiplatform test compilation its main compilation's class directories.
  // So the classpath is resolved when the task runs, every file under the module's build directory
  // is dropped, and the task depends on the tasks that build the rest — other projects' jars.
  val buildDirectory = module.layout.buildDirectory.get().asFile
  val classpath = module.configurations.getByName(shape.libraries)
  val libraries = module.files(module.provider { classpath.files.filterNot { it.startsWith(buildDirectory) } })
  val ownTaskPrefix = if (path == ":") ":" else "$path:"
  task.dependsOn(module.provider {
    classpath.buildDependencies.getDependencies(null)
      .filterNot { it.path.startsWith(ownTaskPrefix) && it.path.indexOf(':', ownTaskPrefix.length) < 0 }
  })

  val kspClasspath = module.configurations.detachedConfiguration(
    module.dependencies.create("com.google.devtools.ksp:symbol-processing-aa-embeddable:$kspVersion"))
  // A file collection rather than the Configuration: the configuration cache refuses a Configuration
  // captured by the argument provider below.
  val processorClasspath = module.files(
    module.configurations.detachedConfiguration(processor.copy()).apply { isTransitive = false })

  val toolchains = module.extensions.getByType(JavaToolchainService::class.java)
  val javaExtension = module.extensions.findByType(JavaPluginExtension::class.java)
  val launcher = if (javaExtension != null) toolchains.launcherFor(javaExtension.toolchain) else toolchains.launcherFor {}
  val jdkHome = launcher.get().metadata.installationPath.asFile.absolutePath
  val out = module.layout.buildDirectory.dir("tmp/printMockApi")
  val projectDirectory = module.projectDir
  val moduleName = module.name

  task.group = "help"
  task.description = "Prints the mock generated for each kspMocksTargets interface, without compiling the module."
  task.classpath = kspClasspath
  task.mainClass.set("com.google.devtools.ksp.cmdline.KSPJvmMain")
  task.javaLauncher.set(launcher)
  task.isIgnoreExitValue = true
  task.inputs.files(sources).withPropertyName("sources")
  task.inputs.files(libraries).withPropertyName("libraries").withNormalizer(ClasspathNormalizer::class.java)
  task.inputs.files(processorClasspath).withPropertyName("processor")
  task.outputs.upToDateWhen { false }
  // KSP's bundled IntelliJ classes call sun.misc.Unsafe, which JDK 23 and newer warn about on every
  // run. Older launchers reject the argument.
  if (launcher.get().metadata.languageVersion.asInt() >= 23) {
    task.jvmArgs("--sun-misc-unsafe-memory-access=allow")
  }
  task.doFirst { out.get().asFile.deleteRecursively() }
  task.argumentProviders.add(CommandLineArgumentProvider {
    val o = out.get().asFile
    buildList {
      add("-module-name=$moduleName")
      // KSPJvmMain requires a target; this run compiles nothing, so no class file carries it.
      add("-jvm-target=17")
      add("-language-version=$languageVersion")
      add("-api-version=$languageVersion")
      add("-jdk-home=$jdkHome")
      add("-source-roots=${sources.asPath}")
      if (!commonSources.isEmpty) add("-common-source-roots=${commonSources.asPath}")
      add("-libraries=${libraries.asPath}")
      add("-project-base-dir=$projectDirectory")
      add("-output-base-dir=$o")
      add("-caches-dir=${o.resolve("caches")}")
      add("-class-output-dir=${o.resolve("classes")}")
      add("-kotlin-output-dir=${o.resolve("kotlin")}")
      add("-java-output-dir=${o.resolve("java")}")
      add("-resource-output-dir=${o.resolve("resources")}")
      add("-processor-options=kspMocksTargets=${targets.joinToString(",")}")
      add(processorClasspath.asPath)
    }
  })
  task.doLast {
    val exitValue = (this as JavaExec).executionResult.get().exitValue
    val generated = out.get().asFile.resolve("kotlin")
    var missing = 0
    for (fqn in targets) {
      // A nested interface's mock is named after its simple name and lands in the enclosing
      // package, so the file is the one whose package directory is the longest prefix of the name.
      val file = generated.walkTopDown()
        .filter { it.name == "${fqn.substringAfterLast('.')}Mock.kt" }
        .map { it to it.parentFile.relativeTo(generated).path.replace(File.separatorChar, '.') }
        .filter { (_, pkg) -> pkg.isEmpty() || fqn.startsWith("$pkg.") }
        .maxByOrNull { (_, pkg) -> pkg.length }
        ?.first
      if (file == null) {
        println("// $fqn: no mock generated")
        println()
        missing++
        continue
      }
      val text = file.readText()
      println("// $fqn")
      print(if (text.endsWith("\n")) text else "$text\n")
      println()
    }
    if (missing > 0 || exitValue != 0) {
      throw GradleException(
        "printMockApi: $path — $missing of ${targets.size} targets generated no mock; " +
          "KSP exited $exitValue, and its diagnostics are printed above")
    }
  }
}

fun <T> reflect(path: String, member: String, lookup: () -> T): T =
  try {
    lookup()
  } catch (e: ReflectiveOperationException) {
    throw GradleException(
      "printMockApi: $path — $member is not available in the applied plugin (${e.javaClass.simpleName}); " +
        "this script reads it by name", e)
  }
