// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

package dev.modaal.mocks

/**
 * Renders a [MockTarget] as Kotlin source, in the cross-platform mock dialect
 * this project shares with its Swift twin (swift-sourcery-templates). One
 * member vocabulary on both platforms:
 *
 * - method → `<fn>CallCount` + `<fn>Args` (single recordable parameter stored
 *   directly, several as a nested `<Fn>Args` data class, function-typed
 *   parameters dropped) + `<fn>Handler`, the only seeding mechanism. Fallback
 *   when the handler is unset: Unit returns nothing, a nullable return is
 *   `null`, a guessable default is returned, a `Flow` return replays the
 *   mock's `<fn>Channel`, anything else fails with
 *   `"<fn>Handler expected to be set."` (the Swift template's exact string).
 * - property → `<prop>GetCount` + `<prop>GetHandler` + the `_<prop>` store the
 *   getter falls back to, on every requirement, and `<prop>SetCount` as well
 *   when the requirement is `var`. A read-only requirement's override is
 *   `val`, so `_<prop>` is the path a test seeds it through.
 * - non-defaultable property → constructor parameter of the declared name,
 *   which seeds `_<prop>` (the constructor-seeded bag; member addition breaks
 *   at compile time).
 * - read-only `Flow` property → `<prop>GetCount` + `<prop>GetHandler` +
 *   `<prop>Channel` fallback (the Swift side's publisher/Subject shape) and no
 *   store: the channel is what a test pushes through.
 * - channel-backed `Flow` member, property or function → `<name>SubscribeCount`
 *   + `<name>SubscribeCancelCount` + `<name>OutputCount` + `<name>Outputs` +
 *   `<name>OutputHandler` + `<name>CompletionCount`, counting what crossed the
 *   member (Combine's words, shared with the Swift side's publisher members).
 *
 * Output is byte-deterministic: members are emitted name-sorted regardless of
 * declaration order, and nothing in the rendering reads clocks, maps with
 * unstable iteration order, or absolute paths.
 */
object MockRenderer {

  /** What one pass produced: the mock source, or the collision that stopped it. */
  sealed interface Rendering {
    data class Rendered(val text: String) : Rendering

    /** Two interface members generate one mock member. [message] is what the
     * processor logs; no file is written. */
    data class Collision(val message: String) : Rendering
  }

  fun render(target: MockTarget): Rendering {
    val mockName = "${target.interfaceName}Mock"
    val properties = target.properties.sortedBy { it.name }
    val functions = withBookkeepingNames(target.functions)

    // A read-only Flow property has no store (its fallback is the channel);
    // every other property keeps a `_<prop>` store, and a store with no
    // guessable default is seeded through the constructor.
    val storedProperties = properties.filterNot { it.isReadOnlyFlow }
    val constructorProperties = storedProperties.filter { it.defaultValue == null }

    val body = StringBuilder()
    val declared = DeclaredNames(target.qualifiedName)
    for (property in properties) {
      val block = renderProperty(property)
      body.append(block)
      declared.claim(block, property.name)
    }
    for ((function, bookkeepingName) in functions) {
      val block = renderFunction(function, bookkeepingName)
      body.append(block)
      declared.claim(block, signature(function))
    }
    declared.collision?.let { return Rendering.Collision(it) }

    val usesChannel =
      properties.any { it.isReadOnlyFlow } || target.functions.any { it.flowElementType != null }

    val text = StringBuilder()
    text.append("// Generated by dev.modaal:mocks-processor. DO NOT EDIT.\n")
    text.append("// Regenerated at test compilation; generated output is never committed.\n")
    text.append("package ${target.packageName}\n\n")
    if (usesChannel) {
      // Extensions cannot be called fully qualified, so the operators the
      // stream counters hang on are imports. `flow`/`emitAll` are the read-only
      // Flow property's builder and nothing else needs them.
      val imports = mutableListOf("onCompletion", "onEach", "onStart", "receiveAsFlow")
      if (properties.any { it.isReadOnlyFlow }) imports += listOf("emitAll", "flow")
      for (import in imports.sorted()) {
        text.append("import kotlinx.coroutines.flow.$import\n")
      }
      text.append("\n")
    }
    if (constructorProperties.isEmpty()) {
      text.append("class $mockName : ${target.qualifiedName} {\n")
    } else {
      text.append("class $mockName(\n")
      for (property in constructorProperties) {
        text.append("  ${property.name}: ${property.renderedType},\n")
      }
      text.append(") : ${target.qualifiedName} {\n")
    }
    text.append(body)
    text.append("}\n")
    return Rendering.Rendered(text.toString())
  }

  /** How a diagnostic names one declaration: `volume`, or `update(id: kotlin.String)`. */
  private fun signature(function: MockFunction): String =
    function.parameters.joinToString(", ", "${function.name}(", ")") {
      "${it.name}: ${it.renderedType}"
    }

  /**
   * Every member name one pass declared, read back out of the text it emitted
   * so that the checked set cannot drift from the emitted one: a `var`, a `val`
   * or a nested `data class` at member indentation. Function overrides are not
   * in it — overloads share a declared name legitimately, and Kotlin allows a
   * property and a function to carry the same name.
   */
  private class DeclaredNames(private val qualifiedName: String) {
    private val owners = mutableMapOf<String, String>()

    /** The first collision found, in emission order; null while there is none. */
    var collision: String? = null
      private set

    fun claim(block: String, owner: String) {
      for (match in DECLARATION.findAll(block)) {
        val name = match.groupValues[1].ifEmpty { match.groupValues[2] }
        val first = owners[name]
        if (first == null) {
          owners[name] = owner
          continue
        }
        if (collision == null) {
          collision =
            "$OPTION: $qualifiedName — $name is generated twice, for $first and for $owner; rename one of the two interface members."
        }
      }
    }

    private companion object {
      /** `  var x`, `  val x`, `  override var x` or `  data class XArgs(`. */
      val DECLARATION =
        Regex(
          """^ {2}(?:override )?va[lr] ([A-Za-z_]\w*)|^ {2}data class ([A-Za-z_]\w*)""",
          RegexOption.MULTILINE)
    }
  }

  private val MockProperty.isReadOnlyFlow: Boolean
    get() = !isMutable && flowElementType != null

  /**
   * Overloads would collide on the shared bookkeeping members
   * (`<fn>CallCount`, …). The overload with the fewest parameters keeps the
   * plain name (adding a wider overload later does not rename existing
   * members); the others append their capitalized parameter names. Overloads
   * this leaves sharing a name (same parameter names, different types) collide
   * on the emitted members, which [DeclaredNames] reports.
   * Result list is sorted by bookkeeping name — the emission order.
   */
  private fun withBookkeepingNames(
    functions: List<MockFunction>
  ): List<Pair<MockFunction, String>> {
    val named =
      functions
        .groupBy { it.name }
        .flatMap { (name, group) ->
          if (group.size == 1) return@flatMap listOf(group.single() to name)
          val ordered =
            group.sortedWith(
              compareBy({ it.parameters.size }, { fn -> fn.parameters.joinToString { it.renderedType } }))
          ordered.mapIndexed { index, fn ->
            if (index == 0) fn to name
            else fn to name + fn.parameters.joinToString("") { it.name.replaceFirstChar(Char::uppercase) }
          }
        }
    return named.sortedBy { it.second }
  }

  private fun renderProperty(property: MockProperty): String {
    val b = StringBuilder()
    val name = property.name
    val type = property.renderedType
    if (property.isReadOnlyFlow) {
      b.append("\n")
      b.append("  override val $name: $type\n")
      b.append("    get() {\n")
      b.append("      ${name}GetCount += 1\n")
      // The handler is read inside the builder rather than here, so one seeded
      // after the code under test captured the flow still decides the stream.
      b.append(
        "      return flow { emitAll(${name}GetHandler?.invoke() ?: ${name}Channel.receiveAsFlow()) }\n")
      b.append(streamOperators(name, "        "))
      b.append("    }\n")
      b.append("  var ${name}GetCount: kotlin.Int = 0\n")
      b.append("  var ${name}GetHandler: (() -> $type)? = null\n")
      b.append(streamMembers(name, property.flowElementType!!))
      return b.toString()
    }
    // Every other requirement is an accessor over the `_<prop>` store, so a
    // read counts and can be handler-driven whether the requirement is stored
    // or computed. The store is seeded from the guessable default, or from the
    // constructor parameter of the declared name when there is none, and
    // construction moves no counter.
    val initial = property.defaultValue ?: property.name
    b.append("\n")
    b.append("  override ${if (property.isMutable) "var" else "val"} $name: $type\n")
    b.append("    get() {\n")
    b.append("      ${name}GetCount += 1\n")
    b.append("      ${name}GetHandler?.let { return it() }\n")
    b.append("      return _${name}\n")
    b.append("    }\n")
    if (property.isMutable) {
      b.append("    set(value) {\n")
      b.append("      ${name}SetCount += 1\n")
      b.append("      _${name} = value\n")
      b.append("    }\n")
    }
    b.append("  var ${name}GetCount: kotlin.Int = 0\n")
    b.append("  var ${name}GetHandler: (() -> $type)? = null\n")
    if (property.isMutable) {
      b.append("  var ${name}SetCount: kotlin.Int = 0\n")
    }
    b.append("  var _${name}: $type = $initial\n")
    return b.toString()
  }

  private fun renderFunction(function: MockFunction, bookkeepingName: String): String {
    val b = StringBuilder()
    val fn = bookkeepingName
    val capitalized = fn.replaceFirstChar(Char::uppercase)
    val recordable = function.parameters.filterNot { it.isFunctionType }
    val isUnit = function.renderedReturnType == "kotlin.Unit"

    val signature =
      function.parameters.joinToString(", ") { "${it.name}: ${it.renderedType}" }
    val forwarded = function.parameters.joinToString(", ") { it.name }
    val suspendKeyword = if (function.isSuspend) "suspend " else ""
    val returnClause = if (isUnit) "" else ": ${function.renderedReturnType}"

    b.append("\n")
    // Several recordable parameters: a nested data class is the args record
    // (Kotlin has no tuples).
    if (recordable.size > 1) {
      b.append("  data class ${capitalized}Args(\n")
      for (parameter in recordable) {
        b.append("    val ${parameter.name}: ${parameter.renderedType},\n")
      }
      b.append("  )\n")
    }

    b.append("  override ${suspendKeyword}fun ${function.name}($signature)$returnClause {\n")
    b.append("    ${fn}CallCount += 1\n")
    // Arguments are recorded before the handler runs: a handler that throws
    // does not un-make the call.
    when {
      recordable.size == 1 -> b.append("    ${fn}Args.add(${recordable.single().name})\n")
      recordable.size > 1 ->
        b.append("    ${fn}Args.add(${capitalized}Args(${recordable.joinToString(", ") { it.name }}))\n")
    }
    if (isUnit) {
      b.append("    ${fn}Handler?.invoke($forwarded)\n")
    } else if (function.flowElementType != null) {
      // The handler stays at call time — that is where the arguments are, and
      // where the member's `suspend` applies — and the counters wrap whichever
      // stream the call produced.
      b.append("    return (${fn}Handler?.invoke($forwarded) ?: ${fn}Channel.receiveAsFlow())\n")
      b.append(streamOperators(fn, "      "))
    } else {
      b.append("    ${fn}Handler?.let { return it($forwarded) }\n")
      when {
        function.returnIsNullable -> b.append("    return null\n")
        function.returnDefault != null -> b.append("    return ${function.returnDefault}\n")
        else -> b.append("    error(\"${fn}Handler expected to be set.\")\n")
      }
    }
    b.append("  }\n")

    b.append("  var ${fn}CallCount: kotlin.Int = 0\n")
    when {
      recordable.size == 1 ->
        b.append(
          "  val ${fn}Args: kotlin.collections.MutableList<${recordable.single().renderedType}> = mutableListOf()\n")
      recordable.size > 1 ->
        b.append("  val ${fn}Args: kotlin.collections.MutableList<${capitalized}Args> = mutableListOf()\n")
    }
    val handlerParams = function.parameters.joinToString(", ") { it.renderedType }
    val handlerType = "$suspendKeyword($handlerParams) -> ${function.renderedReturnType}"
    b.append("  var ${fn}Handler: ($handlerType)? = null\n")
    if (function.flowElementType != null) {
      b.append(streamMembers(fn, function.flowElementType))
    }
    return b.toString()
  }

  /**
   * The operators every channel-backed member's stream carries, hung on the
   * flow the member returns: `<name>SubscribeCount` counts collections,
   * `<name>OutputCount` / `<name>Outputs` / `<name>OutputHandler` see each
   * delivered value in that order, and the end of the stream is counted as a
   * cancellation or as a completion. `kotlinx.coroutines.flow.take`, `first`
   * and a timeout each end a collection with a `CancellationException`, so a
   * collector that stops early counts `<name>SubscribeCancelCount`; a stream
   * that fails counts `<name>CompletionCount`, as a normal end does.
   * None of the counters is synchronized: concurrent collection of one member
   * can lose an increment or a recorded value.
   */
  private fun streamOperators(name: String, indent: String): String {
    val b = StringBuilder()
    b.append("$indent.onStart { ${name}SubscribeCount += 1 }\n")
    b.append("$indent.onEach { value ->\n")
    b.append("$indent  ${name}OutputCount += 1\n")
    b.append("$indent  ${name}Outputs.add(value)\n")
    b.append("$indent  ${name}OutputHandler?.invoke(value)\n")
    b.append("$indent}\n")
    b.append("$indent.onCompletion { cause ->\n")
    b.append(
      "$indent  if (cause is kotlinx.coroutines.CancellationException) ${name}SubscribeCancelCount += 1\n")
    b.append("$indent  else ${name}CompletionCount += 1\n")
    b.append("$indent}\n")
    return b.toString()
  }

  /** What [streamOperators] moves, and the channel the member replays while its
   * handler is unset. */
  private fun streamMembers(name: String, elementType: String): String {
    val b = StringBuilder()
    b.append("  var ${name}SubscribeCount: kotlin.Int = 0\n")
    b.append("  var ${name}SubscribeCancelCount: kotlin.Int = 0\n")
    b.append("  var ${name}OutputCount: kotlin.Int = 0\n")
    b.append("  val ${name}Outputs: kotlin.collections.MutableList<$elementType> = mutableListOf()\n")
    b.append("  var ${name}OutputHandler: (($elementType) -> kotlin.Unit)? = null\n")
    b.append("  var ${name}CompletionCount: kotlin.Int = 0\n")
    b.append("  val ${name}Channel: kotlinx.coroutines.channels.Channel<$elementType> =\n")
    b.append("    kotlinx.coroutines.channels.Channel(kotlinx.coroutines.channels.Channel.UNLIMITED)\n")
    return b.toString()
  }
}
