// Copyright (c) 2026 Modaal.dev
// Licensed under the MIT License. See LICENSE file for details.

package dev.modaal.mocks

/**
 * Renders a [MockTarget] as Kotlin source, in the cross-platform mock dialect
 * this project shares with its Swift twin (swift-sourcery-templates). One
 * member vocabulary on both platforms:
 *
 * - method → `<fn>CallCount` + `<fn>Args` (single recordable parameter stored
 *   directly, several as a nested `<Fn>Args` data class, function-typed
 *   parameters dropped) + `<fn>Handler`, the only seeding mechanism. Fallback
 *   when the handler is unset: Unit returns nothing, a nullable return is
 *   `null`, a guessable default is returned, a `Flow` return replays the
 *   mock's `<fn>Channel`, anything else fails with
 *   `"<fn>Handler expected to be set."` (the Swift template's exact string).
 * - read-only `Flow` property → `<prop>GetCount` + `<prop>GetHandler` +
 *   `<prop>Channel` fallback (the Swift side's publisher/Subject shape).
 * - mutable property → stored value whose setter counts `<prop>SetCount`.
 * - non-defaultable stored property → constructor parameter (the
 *   constructor-seeded bag; member addition breaks at compile time).
 *
 * Output is byte-deterministic: members are emitted name-sorted regardless of
 * declaration order, and nothing in the rendering reads clocks, maps with
 * unstable iteration order, or absolute paths.
 */
object MockRenderer {

  fun render(target: MockTarget): String {
    val mockName = "${target.interfaceName}Mock"
    val properties = target.properties.sortedBy { it.name }
    val functions = withBookkeepingNames(target.functions)

    // Read-only Flow properties are computed (GetHandler/Channel); everything
    // else is stored, and stored members without a guessable default are
    // constructor-seeded.
    val storedProperties = properties.filterNot { it.isReadOnlyFlow }
    val constructorProperties = storedProperties.filter { it.defaultValue == null }

    val body = StringBuilder()
    for (property in properties) {
      body.append(renderProperty(property))
    }
    for ((function, bookkeepingName) in functions) {
      body.append(renderFunction(function, bookkeepingName))
    }

    val usesChannel =
      properties.any { it.isReadOnlyFlow } || target.functions.any { it.flowElementType != null }

    val text = StringBuilder()
    text.append("// Generated by dev.modaal:mocks-processor. DO NOT EDIT.\n")
    text.append("// Regenerated at test compilation; generated output is never committed.\n")
    text.append("package ${target.packageName}\n\n")
    if (usesChannel) {
      text.append("import kotlinx.coroutines.flow.receiveAsFlow\n\n")
    }
    if (constructorProperties.isEmpty()) {
      text.append("class $mockName : ${target.qualifiedName} {\n")
    } else {
      text.append("class $mockName(\n")
      for (property in constructorProperties) {
        text.append("  ${property.name}: ${property.renderedType},\n")
      }
      text.append(") : ${target.qualifiedName} {\n")
    }
    text.append(body)
    text.append("}\n")
    return text.toString()
  }

  private val MockProperty.isReadOnlyFlow: Boolean
    get() = !isMutable && flowElementType != null

  /**
   * Overloads would collide on the shared bookkeeping members
   * (`<fn>CallCount`, …). The overload with the fewest parameters keeps the
   * plain name (adding a wider overload later does not rename existing
   * members); the others append their capitalized parameter names.
   * Result list is sorted by bookkeeping name — the emission order.
   */
  private fun withBookkeepingNames(
    functions: List<MockFunction>
  ): List<Pair<MockFunction, String>> {
    val named =
      functions
        .groupBy { it.name }
        .flatMap { (name, group) ->
          if (group.size == 1) return@flatMap listOf(group.single() to name)
          val ordered =
            group.sortedWith(
              compareBy({ it.parameters.size }, { fn -> fn.parameters.joinToString { it.renderedType } }))
          ordered.mapIndexed { index, fn ->
            if (index == 0) fn to name
            else fn to name + fn.parameters.joinToString("") { it.name.replaceFirstChar(Char::uppercase) }
          }
        }
    val duplicates = named.groupBy { it.second }.filterValues { it.size > 1 }.keys
    require(duplicates.isEmpty()) {
      "overloads collide on bookkeeping names even after parameter-name disambiguation: $duplicates"
    }
    return named.sortedBy { it.second }
  }

  private fun renderProperty(property: MockProperty): String {
    val b = StringBuilder()
    val name = property.name
    val type = property.renderedType
    if (property.isReadOnlyFlow) {
      b.append("\n")
      b.append("  override val $name: $type\n")
      b.append("    get() {\n")
      b.append("      ${name}GetCount += 1\n")
      b.append("      ${name}GetHandler?.let { return it() }\n")
      b.append("      return ${name}Channel.receiveAsFlow()\n")
      b.append("    }\n")
      b.append("  var ${name}GetCount: kotlin.Int = 0\n")
      b.append("  var ${name}GetHandler: (() -> $type)? = null\n")
      b.append(
        "  val ${name}Channel: kotlinx.coroutines.channels.Channel<${property.flowElementType}> =\n")
      b.append(
        "    kotlinx.coroutines.channels.Channel(kotlinx.coroutines.channels.Channel.UNLIMITED)\n")
      return b.toString()
    }
    // Stored: constructor-seeded when there is no guessable default. A
    // read-only requirement is satisfied by a `var` override so a test can
    // re-seed the value directly.
    val initial = property.defaultValue ?: property.name
    b.append("\n")
    if (property.isMutable) {
      b.append("  override var $name: $type = $initial\n")
      b.append("    set(value) {\n")
      b.append("      ${name}SetCount += 1\n")
      b.append("      field = value\n")
      b.append("    }\n")
      b.append("  var ${name}SetCount: kotlin.Int = 0\n")
    } else {
      b.append("  override var $name: $type = $initial\n")
    }
    return b.toString()
  }

  private fun renderFunction(function: MockFunction, bookkeepingName: String): String {
    val b = StringBuilder()
    val fn = bookkeepingName
    val capitalized = fn.replaceFirstChar(Char::uppercase)
    val recordable = function.parameters.filterNot { it.isFunctionType }
    val isUnit = function.renderedReturnType == "kotlin.Unit"

    val signature =
      function.parameters.joinToString(", ") { "${it.name}: ${it.renderedType}" }
    val forwarded = function.parameters.joinToString(", ") { it.name }
    val suspendKeyword = if (function.isSuspend) "suspend " else ""
    val returnClause = if (isUnit) "" else ": ${function.renderedReturnType}"

    b.append("\n")
    // Several recordable parameters: a nested data class is the args record
    // (Kotlin has no tuples).
    if (recordable.size > 1) {
      b.append("  data class ${capitalized}Args(\n")
      for (parameter in recordable) {
        b.append("    val ${parameter.name}: ${parameter.renderedType},\n")
      }
      b.append("  )\n")
    }

    b.append("  override ${suspendKeyword}fun ${function.name}($signature)$returnClause {\n")
    b.append("    ${fn}CallCount += 1\n")
    // Arguments are recorded before the handler runs: a handler that throws
    // does not un-make the call.
    when {
      recordable.size == 1 -> b.append("    ${fn}Args.add(${recordable.single().name})\n")
      recordable.size > 1 ->
        b.append("    ${fn}Args.add(${capitalized}Args(${recordable.joinToString(", ") { it.name }}))\n")
    }
    if (isUnit) {
      b.append("    ${fn}Handler?.invoke($forwarded)\n")
    } else {
      b.append("    ${fn}Handler?.let { return it($forwarded) }\n")
      when {
        function.flowElementType != null ->
          b.append("    return ${fn}Channel.receiveAsFlow()\n")
        function.returnIsNullable -> b.append("    return null\n")
        function.returnDefault != null -> b.append("    return ${function.returnDefault}\n")
        else -> b.append("    error(\"${fn}Handler expected to be set.\")\n")
      }
    }
    b.append("  }\n")

    b.append("  var ${fn}CallCount: kotlin.Int = 0\n")
    when {
      recordable.size == 1 ->
        b.append(
          "  val ${fn}Args: kotlin.collections.MutableList<${recordable.single().renderedType}> = mutableListOf()\n")
      recordable.size > 1 ->
        b.append("  val ${fn}Args: kotlin.collections.MutableList<${capitalized}Args> = mutableListOf()\n")
    }
    val handlerParams = function.parameters.joinToString(", ") { it.renderedType }
    val handlerType = "$suspendKeyword($handlerParams) -> ${function.renderedReturnType}"
    b.append("  var ${fn}Handler: ($handlerType)? = null\n")
    if (function.flowElementType != null) {
      b.append(
        "  val ${fn}Channel: kotlinx.coroutines.channels.Channel<${function.flowElementType}> =\n")
      b.append(
        "    kotlinx.coroutines.channels.Channel(kotlinx.coroutines.channels.Channel.UNLIMITED)\n")
    }
    return b.toString()
  }
}
