#!/usr/bin/env bash
# printMockApi checks — the init script the skill ships,
# skills/kotlin-ksp-mocks/scripts/print-mock-api.init.gradle.kts, run on :receipt and held to the
# mocks this build's own test compilation generated.
#
#   G1  the task's dry run lists no :receipt task but printMockApi — it compiles nothing of the module
#   G2  the task exits 0
#   G3  receipt/build/tmp/printMockApi/kotlin/ holds the same .kt files as
#       receipt/build/generated/ksp/test/kotlin/, byte for byte
#   G4  the printed output carries each generated file whole, after a `// <fqn>` line and before a
#       blank line
#
# Needs a JDK and the output of `./gradlew build`, so ci.yml's `build` job runs it after the build.
#
# Usage:
#   scripts/check-print-mock-api.sh               # after ./gradlew build
#   scripts/check-print-mock-api.sh --self-test   # each check red against a seeded violation
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
INIT="$REPO_DIR/skills/kotlin-ksp-mocks/scripts/print-mock-api.init.gradle.kts"
GENERATED="$REPO_DIR/receipt/build/generated/ksp/test/kotlin"
PRINTED="$REPO_DIR/receipt/build/tmp/printMockApi/kotlin"
MODULE=":receipt"

FAILED=0
fail() {
  printf '✘ %s — %s\n' "$1" "$2" >&2
  FAILED=1
}
ok() { printf '✔ %s — %s\n' "$1" "$2"; }

gradle() { (cd "$REPO_DIR" && ./gradlew --console=plain "$@"); }

# ── the checks, each over the inputs it is given ─────────────────

# $1: init script
check_g1() {
  local output status listed
  set +e
  output="$(gradle -I "$1" "$MODULE:printMockApi" --dry-run 2>&1)"
  status=$?
  set -e
  listed="$(printf '%s\n' "$output" | awk '/^:/ {print $1}' | grep "^$MODULE:" | grep -v "^$MODULE:printMockApi$" || true)"
  if [ "$status" -ne 0 ] || ! printf '%s\n' "$output" | grep -q "^$MODULE:printMockApi "; then
    fail G1 "the dry run exited $status without listing $MODULE:printMockApi:
$output"
  elif [ -n "$listed" ]; then
    fail G1 "the dry run lists tasks of $MODULE, so printMockApi compiles the module:
$listed"
  else
    ok G1 "the dry run lists no $MODULE task but printMockApi"
  fi
}

# $1: init script, $2: file the printed output goes to, $3...: extra Gradle arguments
check_g2() {
  local init="$1" stdout="$2" status
  shift 2
  set +e
  gradle -I "$init" "$MODULE:printMockApi" -q "$@" > "$stdout" 2> "$stdout.err"
  status=$?
  set -e
  if [ "$status" -ne 0 ]; then
    fail G2 "printMockApi exited $status:
$(cat "$stdout.err")"
  else
    ok G2 "printMockApi exited 0"
  fi
}

# $1: generated directory, $2: printed directory
check_g3() {
  local out
  out="$(python3 - "$1" "$2" <<'PY'
import pathlib, sys
generated, printed = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
a = {p.relative_to(generated) for p in generated.rglob('*.kt')}
b = {p.relative_to(printed) for p in printed.rglob('*.kt')} if printed.is_dir() else set()
if not a:
    print(f"{generated} holds no .kt file — run ./gradlew build first")
for f in sorted(a - b):
    print(f"only generated by the test compilation: {f}")
for f in sorted(b - a):
    print(f"only written by printMockApi: {f}")
for f in sorted(a & b):
    if (generated / f).read_bytes() != (printed / f).read_bytes():
        print(f"differs: {f}")
PY
)"
  if [ -n "$out" ]; then
    fail G3 "printMockApi's files are not the test compilation's:
$out"
  else
    ok G3 "printMockApi wrote the test compilation's files, byte for byte"
  fi
}

# $1: generated directory, $2: printed output
check_g4() {
  local out
  out="$(python3 - "$1" "$2" <<'PY'
import pathlib, re, sys
generated, stdout = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]).read_text()
for f in sorted(generated.rglob('*.kt')):
    text = f.read_text()
    package = re.search(r'^package (\S+)$', text, flags=re.M)
    fqn = (package.group(1) + '.' if package else '') + f.stem.removesuffix('Mock')
    if f"// {fqn}\n{text}\n" not in stdout:
        print(f"{f.relative_to(generated)}, after // {fqn}")
PY
)"
  if [ -n "$out" ]; then
    fail G4 "the printed output does not carry a generated file whole:
$out"
  else
    ok G4 "the printed output carries each generated file whole"
  fi
}

run_checks() {
  local init="$1" work="$2"
  shift 2
  [ -d "$GENERATED" ] || { fail G0 "$GENERATED does not exist — run ./gradlew build first"; return; }
  check_g1 "$init"
  check_g2 "$init" "$work/stdout" "$@"
  check_g3 "$GENERATED" "$PRINTED"
  check_g4 "$GENERATED" "$work/stdout"
}

# ── the self-test ────────────────────────────────────────────────
# Each check is run against inputs seeded with exactly one violation of it. G1 and G2 run Gradle on
# a seeded init script or with a seeded property; G3 and G4 compare seeded copies of the outputs.

expect_red() {
  local check="$1" output
  shift
  output="$( (FAILED=0; "$@"; exit "$FAILED") 2>&1 )" && {
    printf '✘ %s stayed green against its seeded violation\n' "$check" >&2
    return 1
  }
  if ! printf '%s\n' "$output" | grep -q "✘ $check "; then
    printf '✘ %s did not report; the run said:\n%s\n' "$check" "$output" >&2
    return 1
  fi
  printf '✔ %s red against its seeded violation\n' "$check"
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if [ "${1:-}" = "--self-test" ]; then
  red=0
  [ -d "$GENERATED" ] || { printf '✘ %s does not exist — run ./gradlew build first\n' "$GENERATED" >&2; exit 1; }

  # G1: the init script makes printMockApi depend on the module's compilation.
  cp "$INIT" "$WORK/g1.init.gradle.kts"
  perl -0pi -e 's/  task\.group = "help"\n/  task.group = "help"\n  task.dependsOn("compileKotlin")\n/' "$WORK/g1.init.gradle.kts"
  expect_red G1 check_g1 "$WORK/g1.init.gradle.kts" || red=1

  # G2: a target that does not resolve, so KSP exits 1.
  expect_red G2 check_g2 "$INIT" "$WORK/g2.stdout" -PmockApiTargets=dev.modaal.mocks.receipt.NotDeclared || red=1

  # G3 and G4 compare copies of a clean run's outputs.
  check_g2 "$INIT" "$WORK/stdout" > /dev/null
  cp -R "$PRINTED" "$WORK/printed"
  first="$(cd "$WORK/printed" && find . -name '*.kt' | sort | head -1)"

  # G3: one byte appended to one printed file.
  printf ' ' >> "$WORK/printed/$first"
  expect_red G3 check_g3 "$GENERATED" "$WORK/printed" || red=1

  # G4: one line dropped from the middle of the printed output.
  lines="$(wc -l < "$WORK/stdout" | tr -d ' ')"
  awk -v drop="$((lines / 2))" 'NR != drop' "$WORK/stdout" > "$WORK/g4.stdout"
  expect_red G4 check_g4 "$GENERATED" "$WORK/g4.stdout" || red=1

  if [ "$red" -ne 0 ]; then
    printf '\n✘ self-test: a check did not go red\n' >&2
    exit 1
  fi
  printf '\n✔ self-test: every check red against its seeded violation\n'
  printf '\nnow the checkout itself:\n'
fi

run_checks "$INIT" "$WORK"
if [ "$FAILED" -ne 0 ]; then
  printf '\n✘ printMockApi checks failed\n' >&2
  exit 1
fi
printf '\n✔ printMockApi checks passed\n'
